name: test

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  rspec:
    uses: r7kamura/workflows/.github/workflows/ruby-rspec.yml@main
  rubocop:
    uses: r7kamura/workflows/.github/workflows/ruby-rubocop.yml@main
